image: ghcr.io/ggml-org/llama.cpp:server
hfRepo: nomic-ai/nomic-embed-text-v1.5-GGUF
hfQuant: F16
servedModelName: nomic-embed-text
contextSize: "2048"
extraArgs:
  - "--pooling"
  - "mean"
  - "--ubatch-size"
  - "2048"
port: 8080

persistentVolume:
  size: 5Gi
  storageClass: longhorn-r1
